name: nnt-gpu
channels:
  - defaults
dependencies:
  - natsort=7.1.1
  - pip=21.2.2
  - python=3.7.11
  - tqdm=4.62.0
  - pip:
    - tensorflow-gpu==2.5.0
    - matplotlib==3.4.2
    - numpy==1.19.5
    - opt-einsum==3.3.0
    - pandas==1.3.1
    - pillow==8.3.1
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - six==1.15.0
